SET @col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'machines' AND COLUMN_NAME = 'deploy_bashrc');
SET @sql = IF(@col = 0, 'ALTER TABLE machines ADD COLUMN deploy_bashrc BOOLEAN NOT NULL DEFAULT TRUE AFTER exclusions', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'machines' AND COLUMN_NAME = 'cleanup_users');
SET @sql = IF(@col = 0, 'ALTER TABLE machines ADD COLUMN cleanup_users BOOLEAN NOT NULL DEFAULT TRUE AFTER deploy_bashrc', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
